title: Product
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              display: Title
              required: true
              validate:
                - required
          -
            handle: text
            field:
              type: textarea
              display: Text
          -
            import: image
      -
        fields:
          -
            import: page_builder
  preview:
    display: Preview
    sections:
      -
        fields:
          -
            import: preview
  seo:
    display: SEO
    sections:
      -
        fields:
          -
            import: seo
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            import: template
